### PR TITLE
fix(lint): jest environnement knex

### PR DESCRIPTION
**Pull request by kwiss**
fix(lint-jest-environnement-knex): fix tslint errors

fix(jest-environnement-knex): array typing

fix(typescript): fix compilation errors

### CODE REVIEW

**Comment by douglasduteil** [comment]
`tslint-config-prettier` is alright a dependency of 
https://github.com/SocialGouv/linters/blob/v0.7.2/packages/tslint-config-recommended/package.json#L29

**Comment by douglasduteil** [comment]
Why a different prettier config ?

**Comment by kwiss** [comment]
> Why a different prettier config ?

there is no prettier config in https://github.com/SocialGouv/linters/

**Comment by kwiss** [comment]
> `tslint-config-prettier` is alright a dependency of
> https://github.com/SocialGouv/linters/blob/v0.7.2/packages/tslint-config-recommended/package.json#L29

ok

**Comment by douglasduteil** [comment]
:up: 
Updated with #204 in it

**Pull request merged**
